"""add bulk restock module

Revision ID: 3673314f1232
Revises: c38ee4b77b78
Create Date: 2026-06-03 19:18:18.872930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3673314f1232'
down_revision = 'c38ee4b77b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('package_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_products_barcode'), ['barcode'], unique=True)

    op.create_table('bulk_restocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulk_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_packages', sa.Integer(), nullable=False),
    sa.Column('package_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bulk_product_id'], ['bulk_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_restocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_restocks_bulk_product_id'), ['bulk_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bulk_restocks_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_restocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_restocks_created_at'))
        batch_op.drop_index(batch_op.f('ix_bulk_restocks_bulk_product_id'))

    op.drop_table('bulk_restocks')
    with op.batch_alter_table('bulk_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_products_barcode'))

    op.drop_table('bulk_products')
    # ### end Alembic commands ###
