"""add sale margin to bulk products

Revision ID: 5dacdaaa3e77
Revises: 3673314f1232
Create Date: 2026-06-04 21:38:48.654883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dacdaaa3e77'
down_revision = '3673314f1232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_products', schema=None) as batch_op:
        batch_op.add_column(
    sa.Column(
        "sale_margin",
        sa.Float(),
        nullable=False,
        server_default="0.4",
    )
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bulk_products', schema=None) as batch_op:
        batch_op.drop_column('sale_margin')

    # ### end Alembic commands ###
