"""add inventory movements

Revision ID: 757793c324d3
Revises: 7ffbda900043
Create Date: 2026-05-18 20:34:16.659074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757793c324d3'
down_revision = '7ffbda900043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('previous_stock', sa.Integer(), nullable=False),
    sa.Column('new_stock', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movements_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_movements_created_at'))

    op.drop_table('inventory_movements')
    # ### end Alembic commands ###
