"""add unique constraint to cart items

Revision ID: da5fe03a389a
Revises: 1507b6296e9a
Create Date: 2026-05-08 23:01:50.838843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5fe03a389a'
down_revision = '1507b6296e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_cart_items_cart_id_product_id', ['cart_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('uq_cart_items_cart_id_product_id', type_='unique')

    # ### end Alembic commands ###
